### ISSUE TITLE
Guardian: Implement no members or connected lightning nodes experience

### ISSUE THREAD

**Issue by okjodom** [fedimint/ui#63]
When there's no members or a connected lightning node, guardian ui should show two message bars showing how to gateway operators can connect to the federation.

![image](https://github.com/fedimint/ui/assets/11217077/3ed30c27-11cf-4e66-a83d-ab506466d17c)

**Tasks:**
- [ ] Implement message bar UX
- [ ] Add appropriate message to show the guardian (clarify messaging and copy)
- [ ] Detect state using guardian api and show / hide message bars

**Ref:**
- [Figma](https://www.figma.com/file/ioeAVbWBc3ow2RaZETatM7/Fedimint?node-id=1982%3A23913&mode=dev)

**Comment by IgboPharaoh** [comment]
I'll like to take up this issue as I have a pr that complements the task here

**Comment by okjodom** [comment]
Out of scope for now, until we have updated MVP designs
